# Generated by Django 3.2.5 on 2021-07-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0002_auto_20210728_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rackmodels',
            options={'verbose_name': 'Модель Rack', 'verbose_name_plural': 'Модели Rack'},
        ),
        migrations.AlterField(
            model_name='moduleinplc',
            name='rack_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plc.rackmodels', verbose_name='Модель Rack'),
        ),
    ]
