# Generated by Django 3.2.6 on 2021-09-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllerfamilies',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='modulemodels',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='moduletypes',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='rackmodels',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='technicalequipments',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='technicalequipmenttypes',
            old_name='photo_location',
            new_name='photo',
        ),
    ]
