# Generated by Django 3.2.6 on 2021-09-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0002_auto_20210904_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('rack_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.racktypes', verbose_name='Тип Rack')),
            ],
            options={
                'verbose_name': 'Тип Rack',
                'verbose_name_plural': 'Типы Rack',
            },
        ),
    ]
