# Generated by Django 3.2.5 on 2021-08-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0002_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc',
            name='controller_family',
        ),
        migrations.RemoveField(
            model_name='plc',
            name='location',
        ),
        migrations.RemoveField(
            model_name='moduleinplc',
            name='plc',
        ),
        migrations.DeleteModel(
            name='PC',
        ),
        migrations.DeleteModel(
            name='PLC',
        ),
    ]
