# Generated by Django 3.2.5 on 2021-08-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('technical_equipments', '0003_auto_20210822_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalEquipmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='TechnicalEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='IP адресс')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.locations', verbose_name='Местоположение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='IP адресс')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.locations', verbose_name='Местоположение')),
                ('technical_equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.technicalequipmenttypes', verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'ПК',
                'verbose_name_plural': 'ПК',
            },
        ),
    ]
