# Generated by Django 3.2.6 on 2021-09-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0003_racktypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racktypes',
            name='rack_type',
        ),
        migrations.AddField(
            model_name='rackmodels',
            name='rack_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.racktypes', verbose_name='Тип Rack'),
        ),
    ]
