# Generated by Django 3.2.5 on 2021-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0004_pc_technicalequipments_technicalequipmenttypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PC',
        ),
    ]
