# Generated by Django 3.2.5 on 2021-08-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0005_delete_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinplc',
            name='plc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.technicalequipments', verbose_name='ПЛК'),
        ),
    ]
