# Generated by Django 3.2.5 on 2021-08-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0006_moduleinplc_plc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalequipments',
            options={'verbose_name': 'Техническое средство', 'verbose_name_plural': 'Технические устройства'},
        ),
        migrations.AddField(
            model_name='technicalequipments',
            name='technical_equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.technicalequipmenttypes', verbose_name='Тип устройства'),
        ),
    ]
