# Generated by Django 3.2.6 on 2021-09-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0007_auto_20210914_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinplc',
            name='module_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.moduletypes', verbose_name='Тип модуля'),
        ),
    ]
