# Generated by Django 3.2.6 on 2021-09-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0008_moduleinplc_module_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinplc',
            options={},
        ),
    ]
