# Generated by Django 3.2.6 on 2021-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0009_alter_moduleinplc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinplc',
            options={'verbose_name': 'Модуль в станции', 'verbose_name_plural': 'Модули в станциях'},
        ),
        migrations.AddField(
            model_name='technicalequipments',
            name='project',
            field=models.CharField(max_length=150, null=True, verbose_name='IP адресс'),
        ),
    ]
