# Generated by Django 3.2.6 on 2021-09-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationcomplex',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='equipmentnames',
            old_name='photo_location',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='equipmenttypes',
            old_name='photo_location',
            new_name='photo',
        ),
    ]
