# Generated by Django 3.2.4 on 2021-07-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_equipments', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Тип сигнала',
                'verbose_name_plural': 'Типы сигналов',
            },
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('marking', models.CharField(max_length=15, verbose_name='Маркировка')),
                ('equipment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factory_equipments.equipmentnames', verbose_name='Наименование оборудования')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factory_equipments.equipmenttypes', verbose_name='Тип оборудования')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.moduleinstations', verbose_name='Модуль в станции')),
                ('signal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='signals.signaltypes', verbose_name='Тип сигнала')),
            ],
            options={
                'verbose_name': 'Сигнал',
                'verbose_name_plural': 'Сигналы',
            },
        ),
    ]
