# Generated by Django 3.2.6 on 2021-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_auto_20210914_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='input_reg',
            new_name='address',
        ),
        migrations.AddField(
            model_name='signals',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
