# Generated by Django 3.2.5 on 2021-08-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical_equipments', '0006_moduleinplc_plc'),
        ('switch_cabinets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchports',
            name='is_trunc',
        ),
        migrations.AddField(
            model_name='switchports',
            name='technical_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='technical_equipments.technicalequipments', verbose_name='Устройство'),
        ),
    ]
